# Generated by Django 4.1.1 on 2022-09-28 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=550, null=True)),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 10, 49, 21, 660556), null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quotes',
                'verbose_name_plural': 'Quotes',
                'db_table': 'Quote',
                'managed': True,
            },
        ),
    ]
