# Generated by Django 4.1.1 on 2022-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imggallery', models.ImageField(default='imggallery.jpg', upload_to='')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gallerys',
                'verbose_name_plural': 'Gallerys',
                'db_table': 'Gallery',
                'managed': True,
            },
        ),
    ]
