# Generated by Django 4.1.1 on 2022-10-07 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 7, 9, 51, 48, 233537), null=True),
        ),
    ]
