# Generated by Django 4.1.1 on 2022-10-08 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Childlove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=550, null=True)),
                ('accordimg', models.ImageField(blank=True, default='accordimg.jpg', null=True, upload_to='')),
                ('accordtitle_1', models.CharField(blank=True, max_length=550, null=True)),
                ('accordtitle_2', models.CharField(blank=True, max_length=550, null=True)),
                ('accordtitle_3', models.CharField(blank=True, max_length=550, null=True)),
                ('accordtitle_4', models.CharField(blank=True, max_length=550, null=True)),
                ('accordbody_1', models.TextField(blank=True, null=True)),
                ('accordbody_2', models.TextField(blank=True, null=True)),
                ('accordbody_3', models.TextField(blank=True, null=True)),
                ('accordbody_4', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 5, 2, 9, 387941), null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Childlove',
                'verbose_name_plural': 'Childloves',
                'db_table': 'Childlove',
                'managed': True,
            },
        ),
    ]
