# Generated by Django 4.1.1 on 2022-10-08 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('body', models.TextField()),
                ('startimg', models.ImageField(blank=True, default='startimg.jpg', null=True, upload_to='')),
                ('number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('number_3', models.CharField(blank=True, max_length=50, null=True)),
                ('name_3', models.CharField(blank=True, max_length=100, null=True)),
                ('number_4', models.CharField(blank=True, max_length=50, null=True)),
                ('name_4', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 8, 51, 54, 253010), null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Start',
                'verbose_name_plural': 'Starts',
                'db_table': 'Start',
                'managed': True,
            },
        ),
    ]
