# Generated by Django 4.1.1 on 2022-09-28 10:16

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 9, 28, 11, 16, 48, 835932))),
                ('blogimg', models.ImageField(default='blogimg.jpg', upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
