# Generated by Django 4.1.1 on 2022-10-06 16:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolequpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('equptimage', models.ImageField(default='equptimage.jpg', upload_to='')),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
