# Generated by Django 4.1.1 on 2022-10-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceimg_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
