# Generated by Django 4.1.1 on 2022-11-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_alter_service_serviceimg_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('donateimg', models.ImageField(upload_to='')),
                ('body', models.TextField()),
                ('title_1', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'donates',
                'verbose_name_plural': 'Donates',
                'db_table': 'donate',
                'managed': True,
            },
        ),
    ]
