# Generated by Django 4.1.1 on 2022-11-10 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'db_table': 'About',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ourmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Ourmission',
                'verbose_name_plural': 'Ourmission',
                'db_table': 'Ourmission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ourvalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Ourvalues',
                'verbose_name_plural': 'Ourvalues',
                'db_table': 'Ourvalues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ourvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Ourvision',
                'verbose_name_plural': 'Ourvision',
                'db_table': 'Ourvision',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='donate',
            name='published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
