# Generated by Django 4.1.1 on 2022-11-10 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_ourvalues_ourvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ourvalues',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ourvision',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
