# Generated by Django 4.1.1 on 2022-11-11 07:35

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_about_date_posted_donate_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donatebanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Donatebanner',
                'verbose_name_plural': 'Donatebanner',
                'db_table': 'Donatebanner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enoughdonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Enoughdonate',
                'verbose_name_plural': 'Enoughdonate',
                'db_table': 'Enoughdonate',
                'managed': True,
            },
        ),
    ]
