# Generated by Django 4.1.1 on 2022-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0010_donatebanner_enoughdonate'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='favicon',
            field=models.ImageField(blank=True, default='about/favicon-96x96.png', null=True, upload_to='about'),
        ),
    ]
