# Generated by Django 4.1.1 on 2022-10-25 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpthekids', '0018_alter_sustainschool_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainschool',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 43, 43, 166843)),
        ),
        migrations.AlterField(
            model_name='sustainschool',
            name='title',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
