# Generated by Django 4.1.1 on 2022-10-26 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpthekids', '0019_alter_sustainschool_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainschool',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 21, 36, 28, 865422)),
        ),
    ]
