# Generated by Django 4.1.1 on 2022-10-26 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpthekids', '0020_alter_sustainschool_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainschool',
            name='sustainimage_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=True),
        ),
        migrations.AlterField(
            model_name='sustainschool',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 22, 11, 0, 825248)),
        ),
    ]
