# Generated by Django 4.1.1 on 2022-10-26 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpthekids', '0021_sustainschool_sustainimage_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainschool',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 22, 23, 22, 835258)),
        ),
    ]
