# Generated by Django 4.1.1 on 2022-10-08 09:19

from django.db import migrations, models
import vulnerable.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('body', models.TextField()),
                ('orphans', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('childlove', models.CharField(max_length=50)),
                ('Vulnerableimg', models.ImageField(blank=True, default='Vulnerableimg.jpg', null=True, upload_to='')),
                ('video', models.FileField(upload_to='videos/%y', validators=[vulnerable.validators.vulnerable_v])),
            ],
            options={
                'verbose_name': 'Vulnerable',
                'verbose_name_plural': 'Vulnerables',
                'db_table': 'Vulnerable',
                'managed': True,
            },
        ),
    ]
