# Generated by Django 4.1.1 on 2022-10-08 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerable',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 10, 30, 30, 406649), null=True),
        ),
        migrations.AddField(
            model_name='vulnerable',
            name='published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
