# Generated by Django 4.1.1 on 2022-10-08 09:47

import datetime
from django.db import migrations, models
import vulnerable.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0002_vulnerable_date_posted_vulnerable_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerable',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 10, 47, 55, 791691), null=True),
        ),
        migrations.AlterField(
            model_name='vulnerable',
            name='video',
            field=models.FileField(blank=True, default='video.mp4', null=True, upload_to='', validators=[vulnerable.validators.vulnerable_v]),
        ),
    ]
