# Generated by Django 4.1.1 on 2022-10-08 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0003_alter_vulnerable_date_posted_alter_vulnerable_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerable',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 11, 45, 34, 916897), null=True),
        ),
    ]
