# Generated by Django 4.1.1 on 2022-10-13 07:27

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0008_vulnerable_slug_alter_vulnerable_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerable',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerable',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 13, 8, 27, 34, 676302), null=True),
        ),
    ]
