# Generated by Django 4.1.1 on 2022-10-07 07:08

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolequpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('equptimage', models.ImageField(default='equptimage.jpg', upload_to='')),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 10, 7, 8, 8, 27, 373071))),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
