# Generated by Django 4.1.1 on 2022-10-26 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprogram', '0019_alter_schoolequpt_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolequpt',
            name='equptimage_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=True),
        ),
        migrations.AlterField(
            model_name='schoolequpt',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 21, 36, 28, 860465)),
        ),
    ]
