# Generated by Django 4.1.1 on 2022-10-26 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprogram', '0020_schoolequpt_equptimage_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolequpt',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 22, 11, 0, 820270)),
        ),
    ]
