# Generated by Django 4.1.1 on 2022-10-07 09:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girlstec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('girltecimage', models.ImageField(blank=True, default='girltecimage.jpg', null=True, upload_to='')),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
