# Generated by Django 4.1.1 on 2022-10-16 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevictims', '0003_alter_climatevictims_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatevictims',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 9, 25, 9, 583475), null=True),
        ),
    ]
