# Generated by Django 4.1.1 on 2022-10-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevictims', '0011_alter_climatevictims_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatevictims',
            name='climatevictimsimg_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='climatevictims',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 26, 23, 12, 16, 976706), null=True),
        ),
    ]
