# Generated by Django 4.1.1 on 2022-10-27 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatevictims', '0012_climatevictims_climatevictimsimg_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatevictims',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 9, 32, 13, 804885), null=True),
        ),
    ]
