# Generated by Django 4.1.1 on 2022-10-08 10:45

import datetime
from django.db import migrations, models
import fighthunger.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighthunger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('body', models.TextField()),
                ('fighthungerimg', models.ImageField(blank=True, default='fighthungerimg.jpg', null=True, upload_to='')),
                ('video', models.FileField(blank=True, default='video.mp4', null=True, upload_to='', validators=[fighthunger.validators.fighthunger_v])),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 8, 11, 45, 34, 916897), null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Fighthunger',
                'verbose_name_plural': 'Fighthungers',
                'db_table': 'Fighthunger',
                'managed': True,
            },
        ),
    ]
