# Generated by Django 4.1.1 on 2022-10-12 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighthunger', '0004_alter_fighthunger_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighthunger',
            name='slug',
            field=models.SlugField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='fighthunger',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 4, 6, 58, 834722), null=True),
        ),
    ]
