# Generated by Django 4.1.1 on 2022-10-09 10:40

import banner.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('video', models.FileField(blank=True, default='video.mp4', null=True, upload_to='', validators=[banner.validators.Banner_v])),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 11, 40, 33, 618920), null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'Banner',
                'managed': True,
            },
        ),
    ]
