# Generated by Django 4.1.1 on 2022-10-27 08:40

import banner.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0015_banner_bannerima_1_banner_bannerimg_banner_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 9, 40, 58, 337522), null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[banner.validators.Banner_v]),
        ),
    ]
