# Generated by Django 4.1.1 on 2022-11-10 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0020_alter_banner_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 10, 10, 52, 52, 313352), null=True),
        ),
    ]
